export const AssetKeys = {
  Atlas: {
    Cats: 'cats-atlas',
    Cosmetics: 'cosmetics-atlas',
  },
  Image: {
    GameBackground: 'game-background',
    MeowBarFill: 'meow-bar-fill',
    MeowBarOutline: 'meow-bar-outline',
    RhythmBarBackground: 'rhythm-bar-background',
    PspspsTarget: 'pspsps-target',
    PspspsElement: 'pspsps-element',
    PspspsElementBall: 'pspsps-element-ball',
    PspspsElementLetters: 'pspsps-element-letters',
    ThemeDefaultBg: 'theme-default-bg',
    ThemeCozyBg: 'theme-cozy-bg',
    ThemeSpookyBg: 'theme-spooky-bg',
    ThemeStageBg: 'theme-stage-bg',
    ThemeForestBg: 'theme-forest-bg',
    ThemeBedroomBg: 'theme-bedroom-bg',
    ThemeBeachBg: 'theme-beach-bg',
    ThemeBlossomBg: 'theme-blossom-bg',
    ThemeCyberpunkBg: 'theme-cyberpunk-bg',
    ThemeCabinBg: 'theme-cabin-bg',
    ThemeArcadeBg: 'theme-arcade-bg',
    ThemeWizardBg: 'theme-wizard-bg',
    ThemeIslandsBg: 'theme-islands-bg',
    ThemeMushroomBg: 'theme-mushroom-bg',
  },
  Audio: {
    Background: 'background-music',
    Pspsps: 'pspsps-sfx',
    ThemeDefaultMusic: 'theme-default-music',
    ThemeCozyMusic: 'theme-cozy-music',
    ThemeSpookyMusic: 'theme-spooky-music',
  },
} as const;
