export const AssetKeys = {
  Atlas: {
    Cats: 'cats-atlas',
    Cosmetics: 'cosmetics-atlas',
  },
  Image: {
    GameBackground: 'game-background',
    MeowBarFill: 'meow-bar-fill',
    MeowBarOutline: 'meow-bar-outline',
    RhythmBarBackground: 'rhythm-bar-background',
    /** White-base (greyscale) version of the rhythm bar — meant to be
     *  tinted to any color cleanly. Used in `Game.drawLanes` so the
     *  sampled bg tints render true instead of multiplying through the
     *  prototype's saturated original. */
    RhythmBarBackgroundWhite: 'rhythm-bar-background-white',
    /** Paws-only mask extracted from RhythmBarBackgroundWhite at scene
     *  init. Bar background is fully transparent; paw shapes are white
     *  so any tint applies as a solid color. Layered on top of the
     *  cat-color bar so toe beans read as SOLID pink instead of a
     *  darkened multiply of the cat color. Generated in Preloader. */
    RhythmBarPaws: 'rhythm-bar-paws',
    PspspsTarget: 'pspsps-target',
    /** White-base hit target — same reason as above. Game tints this
     *  with the sampled lane color so the targets visually anchor each
     *  lane without the prototype's colored undertone leaking through. */
    PspspsTargetWhite: 'pspsps-target-white',
    PspspsElement: 'pspsps-element',
    PspspsElementBall: 'pspsps-element-ball',
    /** White-base falling-note ball — greyscale-stretched so `setTint`
     *  produces a clean colored fuzzball. `Note.configure` paints this
     *  with the per-bg sampled lane tint so notes match their target. */
    PspspsElementBallWhite: 'pspsps-element-ball-white',
    PspspsElementLetters: 'pspsps-element-letters',
    /** Vertical fuzzy capsule — hand-authored to match the fuzzball's
     *  edge treatment. Used by Note for hold tails (narrow) and slide
     *  trails (wider). White-base for tint. */
    PspspsTubeWhite: 'pspsps-tube-white',
    /** Parallel-sided stretchable cylinder generated at preload from
     *  the middle band of PspspsTubeWhite — strips off the rounded
     *  end caps so long-hold tails stretch uniformly without tapering
     *  into points. Note uses this as the tail Image source. */
    TailStretch: 'tail-stretch',
    // Background textures load via Preloader.ts iteration over
    // BACKGROUND_CATALOG — keys live on the catalog entries themselves
    // (`entry.backdropKey`), no per-bg AssetKey needed.
  },
  Audio: {
    Background: 'background-music',
    Pspsps: 'pspsps-sfx',
    ThemeDefaultMusic: 'theme-default-music',
    ThemeCozyMusic: 'theme-cozy-music',
    ThemeSpookyMusic: 'theme-spooky-music',
  },
  Json: {
    /** Per-frame translation deltas for each cat animation. Generated by
     *  the extractor from the cat atlas's spriteSourceSize values. Static
     *  cosmetics ride these to bob with their cat without their own
     *  per-frame art. */
    CatFrameOffsets: 'cat-frame-offsets',
    /** Three dominant colors per bg, sampled from the floor zone of each
     *  themes/<id>-bg.png by the extractor. `Game.drawLanes` uses these
     *  as the lane tint trio so the lanes feel "in the scene" instead of
     *  "UI stamped on top." Falls back to the global LANE_COLORS when
     *  the active bg isn't in the JSON. Shape:
     *  `{ "<id>": ["#rrggbb", "#rrggbb", "#rrggbb"], ... }`. */
    BgLaneColors: 'bg-lane-colors',
  },
} as const;
