// AUTO-GENERATED by scripts/sync-catalog.ts.
// Do not edit by hand — your changes will be overwritten.
// Edit tools/<tool>/*.json via the calibrator instead.


import type { BackingTrack } from './state';

export const BACKING_CATALOG: Record<string, BackingTrack> = {
  "bounce-bloom-1": { id: "bounce-bloom-1", displayName: "Bounce & Bloom", speedLabel: "fast", vibe: "melodic", genre: "bubblegum-pop", mood: "playful", bpm: 130, audioKey: "backing-bounce-bloom-1", loopDurationMs: 62000 },
  "bounce-bloom-2": { id: "bounce-bloom-2", displayName: "Bounce & Bloom (alt)", speedLabel: "fast", vibe: "melodic", genre: "bubblegum-pop", mood: "playful", bpm: 130, audioKey: "backing-bounce-bloom-2", loopDurationMs: 62000 },
  "bouncy-bounce": { id: "bouncy-bounce", displayName: "Bouncy Bounce", speedLabel: "fast", vibe: "melodic", genre: "bubblegum-pop", mood: "playful", bpm: 130, audioKey: "backing-bouncy-bounce", loopDurationMs: 62000 },
  "cinematic-bossa-nova-1": { id: "cinematic-bossa-nova-1", displayName: "Cinematic Bossa Nova", speedLabel: "fast", vibe: "melodic", genre: "bossa-nova", mood: "dramatic", bpm: 130, audioKey: "backing-cinematic-bossa-nova-1", loopDurationMs: 62000 },
  "cinematic-bossa-nova-2": { id: "cinematic-bossa-nova-2", displayName: "Cinematic Bossa Nova (alt)", speedLabel: "fast", vibe: "melodic", genre: "bossa-nova", mood: "dramatic", bpm: 130, audioKey: "backing-cinematic-bossa-nova-2", loopDurationMs: 62000 },
  "midnight-coffee": { id: "midnight-coffee", displayName: "Midnight Coffee", speedLabel: "fast", vibe: "melodic", genre: "lo-fi", mood: "chill", bpm: 130, audioKey: "backing-midnight-coffee", loopDurationMs: 62000 },
  "neon-dash": { id: "neon-dash", displayName: "Neon Dash", speedLabel: "fast", vibe: "melodic", genre: "synthwave", mood: "energetic", bpm: 130, audioKey: "backing-neon-dash", loopDurationMs: 62000 },
  "warmth-in-the-air": { id: "warmth-in-the-air", displayName: "Warmth in the Air", speedLabel: "fast", vibe: "melodic", genre: "acoustic-folk", mood: "romantic", bpm: 130, audioKey: "backing-warmth-in-the-air", loopDurationMs: 62000 },
  "midnight-skyline": { id: "midnight-skyline", displayName: "Midnight Skyline", speedLabel: "fast", vibe: "melodic", genre: "lo-fi", mood: "nostalgic", bpm: 130, audioKey: "backing-midnight-skyline", loopDurationMs: 62000 },
  "midnight-skyline-1": { id: "midnight-skyline-1", displayName: "Midnight Skyline (1)", speedLabel: "fast", vibe: "upbeat", genre: "lo-fi", mood: "nostalgic", bpm: 130, audioKey: "backing-midnight-skyline-1", loopDurationMs: 62000 },
  "neon-horizon": { id: "neon-horizon", displayName: "Neon Horizon", speedLabel: "fast", vibe: "smooth", genre: "synthwave", mood: "dreamy", bpm: 130, audioKey: "backing-neon-horizon", loopDurationMs: 62000 },
  "warmth-in-the-air-1": { id: "warmth-in-the-air-1", displayName: "Warmth in the Air (1)", speedLabel: "fast", vibe: "melodic", genre: "acoustic-folk", mood: "romantic", bpm: 130, audioKey: "backing-warmth-in-the-air-1", loopDurationMs: 62000 },
  "neon-horizon-3": { id: "neon-horizon-3", displayName: "Neon Horizon (3)", speedLabel: "fast", vibe: "melodic", genre: "synthwave", mood: "dreamy", bpm: 130, audioKey: "backing-neon-horizon-3", loopDurationMs: 62000 },
  "neon-pulse": { id: "neon-pulse", displayName: "Neon Pulse", speedLabel: "fast", vibe: "upbeat", genre: "synthwave", mood: "energetic", bpm: 130, audioKey: "backing-neon-pulse", loopDurationMs: 62000 },
  "neon-pulse-1": { id: "neon-pulse-1", displayName: "Neon Pulse (1)", speedLabel: "fast", vibe: "melodic", genre: "synthwave", mood: "energetic", bpm: 130, audioKey: "backing-neon-pulse-1", loopDurationMs: 62000 },
};
