// AUTO-GENERATED by scripts/sync-catalog.ts.
// Do not edit by hand — your changes will be overwritten.
// Edit tools/<tool>/*.json via the calibrator instead.


import type { BackingTrack } from './state';

export const BACKING_CATALOG: Record<string, BackingTrack> = {
  "bounce-bloom-1": { id: "bounce-bloom-1", displayName: "Bounce & Bloom", speedLabel: "fast", vibe: "upbeat", bpm: 130, audioKey: "backing-bounce-bloom-1", loopDurationMs: 30000 },
  "bounce-bloom-2": { id: "bounce-bloom-2", displayName: "Bounce & Bloom (alt)", speedLabel: "fast", vibe: "upbeat", bpm: 130, audioKey: "backing-bounce-bloom-2", loopDurationMs: 30000 },
  "bouncy-bounce": { id: "bouncy-bounce", displayName: "Bouncy Bounce", speedLabel: "fast", vibe: "upbeat", bpm: 130, audioKey: "backing-bouncy-bounce", loopDurationMs: 30000 },
  "cinematic-bossa-nova-1": { id: "cinematic-bossa-nova-1", displayName: "Cinematic Bossa Nova", speedLabel: "fast", vibe: "smooth", bpm: 130, audioKey: "backing-cinematic-bossa-nova-1", loopDurationMs: 30000 },
  "cinematic-bossa-nova-2": { id: "cinematic-bossa-nova-2", displayName: "Cinematic Bossa Nova (alt)", speedLabel: "fast", vibe: "smooth", bpm: 130, audioKey: "backing-cinematic-bossa-nova-2", loopDurationMs: 30000 },
  "midnight-coffee": { id: "midnight-coffee", displayName: "Midnight Coffee", speedLabel: "fast", vibe: "melodic", bpm: 130, audioKey: "backing-midnight-coffee", loopDurationMs: 30000 },
  "neon-dash": { id: "neon-dash", displayName: "Neon Dash", speedLabel: "fast", vibe: "upbeat", bpm: 130, audioKey: "backing-neon-dash", loopDurationMs: 30000 },
};
