// AUTO-GENERATED by scripts/sync-catalog.ts.
// Do not edit by hand — your changes will be overwritten.
// Edit tools/user-management/users.json via the calibrator page instead.

export interface UserOverride {
  /** When true + setAt > player.forcedTutorialClearedAt, force the
   *  player into TutorialOrchestrator on next boot. The orchestrator
   *  flips onboardingDone+forcedTutorialClearedAt on completion so the
   *  override does NOT fire again until Tim re-flips the toggle. */
  tutorialCheck: boolean;
  /** When true + setAt > player.forcedGodmodeAppliedAt, grant max
   *  coins + one of every cat / cosmetic / background once at boot. */
  godmode: boolean;
  /** ms timestamp the calibrator page stamped when the row was last
   *  changed. The override only fires when this is GREATER THAN the
   *  player matching consumed-timestamp, so each fresh flip creates a
   *  new override window. */
  setAt: number;
}

export const USER_OVERRIDES: Readonly<Record<string, UserOverride>> = {
  "timmymmit": { tutorialCheck: false, godmode: true, setAt: 1782869772791 },
};

/** Lookup helper: case-insensitive, returns undefined when the user
 *  has no overrides. */
export function getUserOverride(username: string | null | undefined): UserOverride | undefined {
  if (!username) return undefined;
  return USER_OVERRIDES[username.toLowerCase()];
}
