"""Generate new cat variants from a base cat shape.

Strategy: cat13 (Butters) is a clean grey shorthair with distinct ear-pink + the
new orange-iris eye fix. Its body fur is a clean 5-shade grey palette. We map
those 5 grey shades to new hues to generate single-tone cats, head/body split
cats, and naturalistic-tabby cats — leaving ears, eyes, and outlines untouched.

Outputs to:
  assets-raw/cat<N>/cat<N>_<anim>_<NN>.png  (one new cat dir per variant)
  tools/cats/cats.json  (appends stub entries with autogenerated names)

Usage:
  python3 scripts/gen-cat-variants.py        # generates the full curated set
  python3 scripts/gen-cat-variants.py --dry  # report what would be made
"""
import colorsys
import json
import shutil
import sys
from pathlib import Path
from PIL import Image
import numpy as np

ROOT = Path('.')
RAW = ROOT / 'assets-raw'
BASE_CAT = 'cat13'  # Butters — clean grey body, eye-fix applied
CATS_JSON = ROOT / 'tools/cats/cats.json'

# Pixel colors that must NEVER be recolored — eyes, ear pink, outline, etc.
# Captured from cat13 after eye-fix. Anything not in BASE_FUR_PALETTE
# is left untouched in the output frames.
BASE_FUR_PALETTE = [
    (125, 136, 150),  # lightest body
    (117, 128, 144),  # light-mid body
    (90, 100, 113),   # mid body
    (74, 83, 96),     # dark body
    (42, 49, 58),     # darkest body shade
]

# Tone-mapping helper — for a base RGB, return its HSL.
def rgb_to_hls(r, g, b):
    return colorsys.rgb_to_hls(r / 255.0, g / 255.0, b / 255.0)


def hls_to_rgb(h, l, s):
    r, g, b = colorsys.hls_to_rgb(h, l, s)
    return (int(round(r * 255)), int(round(g * 255)), int(round(b * 255)))


def shift_palette(palette, target_h_deg, target_s):
    """Map each base shade to the new hue, preserving original lightness ordering.
    Saturation is set to target_s for all shades (so all variants are consistent)."""
    out = []
    for (r, g, b) in palette:
        h, l, s = rgb_to_hls(r, g, b)
        out.append(hls_to_rgb(target_h_deg / 360.0, l, target_s))
    return out


def shift_palette_naturalistic(palette, target_h_deg, target_s_base):
    """For subtle/natural cat colors — keep low saturation, just shift hue.
    target_s_base is a multiplier (0..1) on natural fur saturation."""
    out = []
    for (r, g, b) in palette:
        h, l, s = rgb_to_hls(r, g, b)
        # Naturalistic: cap saturation, keep desaturated overall
        new_s = min(target_s_base, s + 0.25)
        out.append(hls_to_rgb(target_h_deg / 360.0, l, new_s))
    return out


# Curated variant catalog.
# Each entry: (name, kind, params)
#   kind='solid'    params=(hue_deg, saturation)
#   kind='split'    params=(head_hue, head_sat, body_hue, body_sat)
#   kind='natural'  params=(hue_deg, saturation_cap)
VARIANTS = [
    # ---- Bright single-tone ----
    ('Goldie',     'solid',   (45, 0.95)),    # pure gold
    ('Ruby',       'solid',   (0, 0.85)),     # vivid red
    ('Coral',      'solid',   (15, 0.8)),     # bright coral
    ('Tangerine',  'solid',   (30, 0.95)),    # vivid orange
    ('Lemon',      'solid',   (55, 0.95)),    # bright yellow
    ('Neon',       'solid',   (90, 0.95)),    # neon lime
    ('Mint',       'solid',   (160, 0.6)),    # mint
    ('Cyan',       'solid',   (180, 0.85)),   # bright cyan
    ('Sapphire',   'solid',   (220, 0.85)),   # royal blue
    ('Violet',     'solid',   (270, 0.75)),   # vivid purple
    ('Magenta',    'solid',   (320, 0.85)),   # bright magenta
    ('Bubblegum',  'solid',   (335, 0.7)),    # bubblegum pink

    # ---- Two-tone HEAD/BODY split ----
    ('Sunset',     'split',   (30, 0.85, 320, 0.7)),    # orange head, magenta body
    ('Ocean',      'split',   (180, 0.75, 220, 0.85)),  # cyan head, blue body
    ('Forest',     'split',   (90, 0.55, 30, 0.6)),     # green head, brown body
    ('Royal',      'split',   (270, 0.75, 45, 0.9)),    # purple head, gold body
    ('Watermelon', 'split',   (0, 0.85, 120, 0.7)),     # red head, green body
    ('Berry',      'split',   (320, 0.75, 270, 0.7)),   # pink head, purple body
    ('Aurora',     'split',   (180, 0.75, 270, 0.7)),   # cyan head, purple body
    ('Sundae',     'split',   (15, 0.7, 0, 0.0)),       # coral head, white body
    ('Twix',       'split',   (30, 0.4, 30, 0.7)),      # cream head, caramel body
    ('Inkwell',    'split',   (0, 0.0, 220, 0.85)),     # white head, blue body
    ('Tuxedo',     'split',   (0, 0.0, 0, 0.0)),        # full white (override below)
    ('Cookie',     'split',   (30, 0.4, 30, 0.0)),      # cream head, white body

    # ---- Subtle natural cat colors ----
    ('Cinnamon',   'natural', (25, 0.45)),    # warm brown
    ('Russet',     'natural', (18, 0.5)),     # darker rusty brown
    ('Caramel',    'natural', (30, 0.4)),     # soft caramel
    ('Smoke',      'natural', (220, 0.18)),   # slightly blue-cast grey
    ('Misty',      'natural', (200, 0.15)),   # very pale blue-grey
    ('Sand',       'natural', (40, 0.35)),    # sandy beige
    ('Mocha',      'natural', (20, 0.5)),     # mocha brown
    ('Pewter',     'natural', (240, 0.12)),   # cool grey
    ('Dust',       'natural', (35, 0.2)),     # dust grey-tan
    ('Slate',      'natural', (210, 0.25)),   # darker blue-slate
    ('Frost',      'natural', (0, 0.0)),      # near white
    ('Charcoal',   'natural', (0, 0.0)),      # dark charcoal (lightness shift)

    # ---- A few specials ----
    ('Pearl',      'solid',   (210, 0.1)),    # nearly white with cool tint
    ('Bronze',     'solid',   (25, 0.75)),    # warm bronze
    ('Lavender',   'solid',   (280, 0.45)),   # soft lavender
    ('Peachy',     'solid',   (20, 0.55)),    # soft peach
]


def build_pixel_map(base_palette, target_palette) -> dict:
    return {base: tgt for base, tgt in zip(base_palette, target_palette)}


def recolor_frame_solid(a: np.ndarray, pmap: dict) -> np.ndarray:
    out = a.copy()
    h, w = a.shape[:2]
    # Use vectorized lookup
    r = a[..., 0]
    g = a[..., 1]
    b = a[..., 2]
    alpha = a[..., 3]
    for src, tgt in pmap.items():
        mask = (r == src[0]) & (g == src[1]) & (b == src[2]) & (alpha > 0)
        out[mask, 0] = tgt[0]
        out[mask, 1] = tgt[1]
        out[mask, 2] = tgt[2]
    return out


def recolor_frame_split(a: np.ndarray, head_map: dict, body_map: dict, split_y: int) -> np.ndarray:
    """Apply head_map to rows 0..split_y-1, body_map to rows split_y..end."""
    out = a.copy()
    r = a[..., 0]
    g = a[..., 1]
    b = a[..., 2]
    alpha = a[..., 3]
    ys = np.arange(a.shape[0])[:, None]
    head_mask = ys < split_y
    body_mask = ~head_mask
    for src, tgt in head_map.items():
        m = (r == src[0]) & (g == src[1]) & (b == src[2]) & (alpha > 0) & head_mask
        out[m, 0] = tgt[0]
        out[m, 1] = tgt[1]
        out[m, 2] = tgt[2]
    for src, tgt in body_map.items():
        m = (r == src[0]) & (g == src[1]) & (b == src[2]) & (alpha > 0) & body_mask
        out[m, 0] = tgt[0]
        out[m, 1] = tgt[1]
        out[m, 2] = tgt[2]
    return out


def find_next_cat_id() -> int:
    existing = [int(p.name[3:]) for p in RAW.iterdir() if p.is_dir() and p.name.startswith('cat') and p.name[3:].isdigit()]
    return max(existing) + 1


def load_cats_json() -> list:
    return json.loads(CATS_JSON.read_text())


def save_cats_json(data: list):
    CATS_JSON.write_text(json.dumps(data, indent=2) + '\n')


def make_one_variant(name: str, kind: str, params, new_id: int, dry: bool = False) -> dict:
    new_cat = f'cat{new_id}'
    src_dir = RAW / BASE_CAT
    dst_dir = RAW / new_cat
    if dry:
        return {'name': name, 'id': new_cat, 'kind': kind, 'params': params}

    dst_dir.mkdir(parents=True, exist_ok=True)
    if kind == 'solid':
        hue, sat = params
        tgt = shift_palette(BASE_FUR_PALETTE, hue, sat)
        pmap = build_pixel_map(BASE_FUR_PALETTE, tgt)
        for fp in sorted(src_dir.glob(f'{BASE_CAT}_*.png')):
            a = np.array(Image.open(fp).convert('RGBA'))
            out = recolor_frame_solid(a, pmap)
            out_name = fp.name.replace(BASE_CAT, new_cat)
            Image.fromarray(out, 'RGBA').save(dst_dir / out_name)

    elif kind == 'split':
        h_hue, h_sat, b_hue, b_sat = params
        h_tgt = shift_palette(BASE_FUR_PALETTE, h_hue, h_sat)
        b_tgt = shift_palette(BASE_FUR_PALETTE, b_hue, b_sat)
        h_map = build_pixel_map(BASE_FUR_PALETTE, h_tgt)
        b_map = build_pixel_map(BASE_FUR_PALETTE, b_tgt)
        # Split at y=36 — cat head/face above, body/legs below
        for fp in sorted(src_dir.glob(f'{BASE_CAT}_*.png')):
            a = np.array(Image.open(fp).convert('RGBA'))
            out = recolor_frame_split(a, h_map, b_map, split_y=36)
            out_name = fp.name.replace(BASE_CAT, new_cat)
            Image.fromarray(out, 'RGBA').save(dst_dir / out_name)

    elif kind == 'natural':
        hue, sat = params
        tgt = shift_palette_naturalistic(BASE_FUR_PALETTE, hue, sat)
        pmap = build_pixel_map(BASE_FUR_PALETTE, tgt)
        for fp in sorted(src_dir.glob(f'{BASE_CAT}_*.png')):
            a = np.array(Image.open(fp).convert('RGBA'))
            out = recolor_frame_solid(a, pmap)
            out_name = fp.name.replace(BASE_CAT, new_cat)
            Image.fromarray(out, 'RGBA').save(dst_dir / out_name)
    else:
        raise ValueError(f'unknown kind: {kind}')

    return {'name': name, 'id': new_cat, 'kind': kind, 'params': params}


def main():
    dry = '--dry' in sys.argv

    next_id = find_next_cat_id()
    print(f'Next available cat ID: cat{next_id}')
    print(f'Base cat: {BASE_CAT}')
    print(f'Variants to generate: {len(VARIANTS)}\n')

    cats_data = load_cats_json()
    existing_ids = {c['id'] for c in cats_data}
    print(f'Current cats.json entries: {len(cats_data)}')

    results = []
    cur_id = next_id
    for name, kind, params in VARIANTS:
        r = make_one_variant(name, kind, params, cur_id, dry=dry)
        results.append(r)
        print(f'  cat{cur_id:3d}  {name:12s}  {kind:8s}  {params}')
        cur_id += 1

    # Append to cats.json
    if not dry:
        for r in results:
            if r['id'] in existing_ids:
                continue
            cats_data.append({
                'id': r['id'],
                'name': r['name'],
                'rarity': 'common',
            })
        save_cats_json(cats_data)
        print(f'\ncats.json updated. New total: {len(cats_data)} entries.')

    print(f'\nGenerated {len(results)} variants. Highest new cat: cat{cur_id - 1}')


if __name__ == '__main__':
    main()
