/*
 * Reads the calibrator's JSON output and regenerates the catalogs that
 * the game's shared state imports:
 *
 *   tools/cosmetics/cosmetics.json      →  src/shared/cosmetics-catalog.generated.ts
 *   tools/cats/cats.json                →  src/shared/cats-catalog.generated.ts
 *   tools/themes/themes.json            →  src/shared/themes-catalog.generated.ts
 *   tools/music/music.json              →  src/shared/music-catalog.generated.ts
 *
 * The tools server runs this after every successful POST /save so the
 * game's catalog stays in lock-step with the calibrators without any
 * manual editing. Also runnable directly: `npm run sync:catalog`.
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const PROJECT_ROOT = path.resolve(import.meta.dirname, '..');
const COSMETICS_JSON = path.join(PROJECT_ROOT, 'tools', 'cosmetics', 'cosmetics.json');
const CATS_JSON = path.join(PROJECT_ROOT, 'tools', 'cats', 'cats.json');
// TODO Phase 5: DECORATIONS_JSON removed with decoration system
const THEMES_JSON = path.join(PROJECT_ROOT, 'tools', 'themes', 'themes.json');
const MUSIC_JSON = path.join(PROJECT_ROOT, 'tools', 'music', 'music.json');
const OUT_DIR = path.join(PROJECT_ROOT, 'src', 'shared');

interface CosmeticJsonEntry {
  id: string;
  name: string;
  rarity: string;
  slot?: string;
  scale?: number;
  offsetX?: number;
  offsetY?: number;
  sourceFrame?: string;
  tint?: string;
  tintMode?: string;
  /** When true, this cosmetic has no per-frame animation art and the
   *  game's Cat entity rides it through the cat's per-frame translation
   *  offsets (read from cat-frame-offsets.json) so the cosmetic bobs /
   *  jumps with its cat. Set automatically by the Cosmetic Quick Add
   *  upload flow for single-PNG cosmetics. Defaults to false — existing
   *  hand-animated cosmetics keep their per-frame art driving motion. */
  isStatic?: boolean;
  /** Optional per-cosmetic override of the slot-default motion strength.
   *  1.0 = tracks the cat 1:1, 0 = doesn't ride motion at all. Only
   *  used when `isStatic: true`. */
  motionStrength?: number;
}

interface CatJsonEntry {
  id: string;
  name: string;
  rarity: string;
  scale?: number;
  sourceFrame?: string;
  tint?: string;
  tintMode?: string;
}

// TODO Phase 5: DecorationJsonEntry removed with decoration system

interface ThemeJsonEntry {
  displayName: string;
  backdropKey: string;
  musicKey: string;
  rarity: string;
  // Per-bg vertical shift in DESIGN pixels — positive shifts the bg image
  // UP so platforms in the source PNG align with the cat seats at design
  // y=184. Calibrated via tools/themes/calibrator.html. Default 0.
  bgShiftUp?: number;
  // Per-bg uniform scale multiplier — > 1 crops the edges (zoom in on
  // the platforms), < 1 leaves empty space around the edges. Default 1.
  bgScale?: number;
}

const BANNER =
  '// AUTO-GENERATED by scripts/sync-catalog.ts.\n' +
  '// Do not edit by hand — your changes will be overwritten.\n' +
  '// Edit tools/<tool>/*.json via the calibrator instead.\n';

function fieldLines(fields: Record<string, unknown>): string[] {
  const out: string[] = [];
  for (const [k, v] of Object.entries(fields)) {
    if (v === undefined || v === null) continue;
    out.push(`    ${k}: ${JSON.stringify(v)},`);
  }
  return out;
}

async function readJsonOrEmpty<T>(file: string): Promise<T[]> {
  try {
    const text = await fs.readFile(file, 'utf8');
    const parsed = JSON.parse(text);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

async function genCosmetics(): Promise<number> {
  const arr = await readJsonOrEmpty<CosmeticJsonEntry>(COSMETICS_JSON);
  const lines: string[] = [
    BANNER,
    `import type { CosmeticEntry } from './state';`,
    '',
    `export const GENERATED_COSMETIC_CATALOG: readonly CosmeticEntry[] = [`,
  ];
  for (const e of arr) {
    lines.push('  {');
    lines.push(
      ...fieldLines({
        id: e.id,
        name: e.name,
        rarity: e.rarity,
        slot: e.slot,
        sourceFrame: e.sourceFrame,
        tint: e.tint,
        tintMode: e.tintMode,
        isStatic: e.isStatic,
        motionStrength: e.motionStrength,
      }),
    );
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');
  await fs.writeFile(
    path.join(OUT_DIR, 'cosmetics-catalog.generated.ts'),
    lines.join('\n'),
  );
  return arr.length;
}

async function genCats(): Promise<number> {
  const arr = await readJsonOrEmpty<CatJsonEntry>(CATS_JSON);
  // If cats.json doesn't exist yet, ship the 6 base cats as defaults so the
  // game has something to work with until the cat calibrator gets used.
  const entries: CatJsonEntry[] = arr.length > 0 ? arr : [
    { id: 'cat1', name: 'Mochi', rarity: 'common' },
    { id: 'cat2', name: 'Biscuit', rarity: 'common' },
    { id: 'cat3', name: 'Pebble', rarity: 'common' },
    { id: 'cat4', name: 'Marble', rarity: 'uncommon' },
    { id: 'cat5', name: 'Saffron', rarity: 'rare' },
    { id: 'cat6', name: 'Inkwell', rarity: 'rare' },
    { id: 'rainbow', name: 'Rainbow Whiskers', rarity: 'legendary' },
  ];
  const lines: string[] = [
    BANNER,
    `import type { CatEntry } from './state';`,
    '',
    `export const GENERATED_CAT_CATALOG: readonly CatEntry[] = [`,
  ];
  for (const e of entries) {
    lines.push('  {');
    lines.push(
      ...fieldLines({
        id: e.id,
        name: e.name,
        rarity: e.rarity,
        scale: e.scale,
        sourceFrame: e.sourceFrame,
        tint: e.tint,
        tintMode: e.tintMode,
      }),
    );
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');
  await fs.writeFile(
    path.join(OUT_DIR, 'cats-catalog.generated.ts'),
    lines.join('\n'),
  );
  return entries.length;
}

// TODO Phase 5: genDecorations() removed with decoration system

async function genThemes(): Promise<number> {
  let raw: Record<string, ThemeJsonEntry> = {};
  try {
    const text = await fs.readFile(THEMES_JSON, 'utf8');
    raw = JSON.parse(text) as Record<string, ThemeJsonEntry>;
  } catch {
    // file not found — write an empty catalog
  }
  const entries = Object.entries(raw);
  const catalogLines: string[] = [];
  for (const [id, v] of entries) {
    const optional: string[] = [];
    if (typeof v.bgShiftUp === 'number') optional.push(`bgShiftUp: ${v.bgShiftUp}`);
    if (typeof v.bgScale === 'number') optional.push(`bgScale: ${v.bgScale}`);
    const optionalStr = optional.length > 0 ? `, ${optional.join(', ')}` : '';
    // JSON.stringify the key so hyphenated ids ("hidden-oasis-cave")
    // emit as ["hidden-oasis-cave"]: instead of an unquoted hidden-oasis-cave:
    // which is a vite/rolldown parse error. Same below for the array-items
    // access form.
    catalogLines.push(
      `  ${JSON.stringify(id)}: { id: ${JSON.stringify(id)}, displayName: ${JSON.stringify(v.displayName)}, backdropKey: ${JSON.stringify(v.backdropKey)}, musicKey: ${JSON.stringify(v.musicKey)}, rarity: ${JSON.stringify(v.rarity)} as const${optionalStr} },`,
    );
  }
  const arrayItems = entries.map(([id]) => `  BACKGROUND_CATALOG[${JSON.stringify(id)}],`);
  const lines: string[] = [
    BANNER,
    '',
    `export const BACKGROUND_CATALOG = {`,
    ...catalogLines,
    `} as const;`,
    '',
    `// Legacy alias — keep so existing THEME_CATALOG consumers compile without a rename sweep.`,
    `// TODO Phase 5 Task 15: remove this alias once all consumers migrate to BACKGROUND_CATALOG.`,
    `export const GENERATED_THEME_CATALOG = [`,
    ...arrayItems,
    `] as const;`,
    '',
  ];
  await fs.writeFile(
    path.join(OUT_DIR, 'themes-catalog.generated.ts'),
    lines.join('\n'),
  );
  return entries.length;
}

interface MusicJsonEntry {
  id: string;
  displayName?: string;
  speedLabel: 'slow' | 'medium' | 'fast' | 'faster';
  vibe: 'upbeat' | 'melodic' | 'smooth';
  /** Musical genre slug — must match BackingGenre union in state.ts.
   *  Optional so old entries pre-genre-system still validate. */
  genre?: string;
  /** Emotional mood slug — must match BackingMood union in state.ts. */
  mood?: string;
  bpm: number;
  loopDurationMs?: number;
  /** Auto-detected (or Tim-overridden) start time of the clip inside
   *  the source mp3. Optional — old entries pre-section-finder lack it. */
  clipStartS?: number;
}

async function genMusic(): Promise<number> {
  let raw: Record<string, MusicJsonEntry> = {};
  try {
    const text = await fs.readFile(MUSIC_JSON, 'utf8');
    raw = JSON.parse(text) as Record<string, MusicJsonEntry>;
  } catch {
    // missing or unparseable — write an empty catalog so MusicSystem stays silent
  }
  // Read user-extensible taxonomies (vibes/genres/moods) so the game's
  // SongPicker can offer any custom values Tim added via the
  // calibrator. Falls back to the canonical seed if the file's missing.
  let tax: { vibes?: string[]; genres?: string[]; moods?: string[] } = {};
  try {
    const taxText = await fs.readFile(
      path.join(PROJECT_ROOT, 'tools', 'music', 'taxonomies.json'),
      'utf8',
    );
    tax = JSON.parse(taxText) as typeof tax;
  } catch {
    // missing — use defaults below
  }
  const vibes = tax.vibes ?? ['upbeat', 'melodic', 'smooth'];
  const genres = tax.genres ?? [
    'bubblegum-pop', 'synthwave', 'lo-fi', 'bossa-nova', 'acoustic-folk',
    'chiptune', 'jazz', 'funk', 'ambient', 'house',
    'rock', 'dance-pop', 'trance', 'hip-hop', 'world',
  ];
  const moods = tax.moods ?? [
    'energetic', 'chill', 'playful', 'romantic', 'mysterious',
    'dramatic', 'nostalgic', 'bright', 'dark', 'dreamy',
  ];
  const entries = Object.entries(raw);
  const catalogLines: string[] = [];
  for (const [id, v] of entries) {
    const loopDur = typeof v.loopDurationMs === 'number' ? v.loopDurationMs : 30_000;
    const genrePart = v.genre ? `, genre: ${JSON.stringify(v.genre)}` : '';
    const moodPart = v.mood ? `, mood: ${JSON.stringify(v.mood)}` : '';
    const clipStartPart = typeof v.clipStartS === 'number' ? `, clipStartS: ${v.clipStartS}` : '';
    catalogLines.push(
      `  ${JSON.stringify(id)}: { id: ${JSON.stringify(id)}, displayName: ${JSON.stringify(v.displayName ?? id)}, speedLabel: ${JSON.stringify(v.speedLabel)}, vibe: ${JSON.stringify(v.vibe)}${genrePart}${moodPart}, bpm: ${v.bpm}, audioKey: ${JSON.stringify('backing-' + id)}, loopDurationMs: ${loopDur}${clipStartPart} },`,
    );
  }
  const lines: string[] = [
    BANNER,
    '',
    `import type { BackingTrack } from './state';`,
    '',
    `// User-extensible taxonomies sourced from tools/music/taxonomies.json.`,
    `// SongPicker + calibrator read these to populate genre/mood/vibe pickers.`,
    `export const BACKING_VIBES: readonly string[] = ${JSON.stringify(vibes)};`,
    `export const BACKING_GENRES: readonly string[] = ${JSON.stringify(genres)};`,
    `export const BACKING_MOODS: readonly string[] = ${JSON.stringify(moods)};`,
    '',
    `export const BACKING_CATALOG: Record<string, BackingTrack> = {`,
    ...catalogLines,
    `};`,
    '',
  ];
  await fs.writeFile(
    path.join(OUT_DIR, 'music-catalog.generated.ts'),
    lines.join('\n'),
  );
  return entries.length;
}

async function main(): Promise<void> {
  await fs.mkdir(OUT_DIR, { recursive: true });
  const [cosCount, catCount, themCount, musicCount] = await Promise.all([
    genCosmetics(),
    genCats(),
    genThemes(),
    genMusic(),
  ]);
  console.log(`[sync] cosmetics=${cosCount} cats=${catCount} themes=${themCount} music=${musicCount}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
