/*
 * Reads the calibrator's JSON output and regenerates the catalogs that
 * the game's shared state imports:
 *
 *   tools/cosmetics/cosmetics.json      →  src/shared/cosmetics-catalog.generated.ts
 *   tools/cats/cats.json                →  src/shared/cats-catalog.generated.ts
 *   tools/decorations/decorations.json  →  src/shared/decorations-catalog.generated.ts
 *
 * The tools server runs this after every successful POST /save so the
 * game's catalog stays in lock-step with the calibrators without any
 * manual editing. Also runnable directly: `npm run sync:catalog`.
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const PROJECT_ROOT = path.resolve(import.meta.dirname, '..');
const COSMETICS_JSON = path.join(PROJECT_ROOT, 'tools', 'cosmetics', 'cosmetics.json');
const CATS_JSON = path.join(PROJECT_ROOT, 'tools', 'cats', 'cats.json');
const DECORATIONS_JSON = path.join(PROJECT_ROOT, 'tools', 'decorations', 'decorations.json');
const OUT_DIR = path.join(PROJECT_ROOT, 'src', 'shared');

interface CosmeticJsonEntry {
  id: string;
  name: string;
  rarity: string;
  slot?: string;
  scale?: number;
  offsetX?: number;
  offsetY?: number;
  sourceFrame?: string;
  tint?: string;
  tintMode?: string;
}

interface CatJsonEntry {
  id: string;
  name: string;
  rarity: string;
  scale?: number;
  sourceFrame?: string;
  tint?: string;
  tintMode?: string;
}

interface DecorationJsonEntry {
  displayName: string;
  frame: string;
  rarity: string;
}

const BANNER =
  '// AUTO-GENERATED by scripts/sync-catalog.ts.\n' +
  '// Do not edit by hand — your changes will be overwritten.\n' +
  '// Edit tools/<tool>/*.json via the calibrator instead.\n';

function fieldLines(fields: Record<string, unknown>): string[] {
  const out: string[] = [];
  for (const [k, v] of Object.entries(fields)) {
    if (v === undefined || v === null) continue;
    out.push(`    ${k}: ${JSON.stringify(v)},`);
  }
  return out;
}

async function readJsonOrEmpty<T>(file: string): Promise<T[]> {
  try {
    const text = await fs.readFile(file, 'utf8');
    const parsed = JSON.parse(text);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

async function genCosmetics(): Promise<number> {
  const arr = await readJsonOrEmpty<CosmeticJsonEntry>(COSMETICS_JSON);
  const lines: string[] = [
    BANNER,
    `import type { CosmeticEntry } from './state';`,
    '',
    `export const GENERATED_COSMETIC_CATALOG: readonly CosmeticEntry[] = [`,
  ];
  for (const e of arr) {
    lines.push('  {');
    lines.push(
      ...fieldLines({
        id: e.id,
        name: e.name,
        rarity: e.rarity,
        slot: e.slot,
        sourceFrame: e.sourceFrame,
        tint: e.tint,
        tintMode: e.tintMode,
      }),
    );
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');
  await fs.writeFile(
    path.join(OUT_DIR, 'cosmetics-catalog.generated.ts'),
    lines.join('\n'),
  );
  return arr.length;
}

async function genCats(): Promise<number> {
  const arr = await readJsonOrEmpty<CatJsonEntry>(CATS_JSON);
  // If cats.json doesn't exist yet, ship the 6 base cats as defaults so the
  // game has something to work with until the cat calibrator gets used.
  const entries: CatJsonEntry[] = arr.length > 0 ? arr : [
    { id: 'cat1', name: 'Mochi', rarity: 'common' },
    { id: 'cat2', name: 'Biscuit', rarity: 'common' },
    { id: 'cat3', name: 'Pebble', rarity: 'common' },
    { id: 'cat4', name: 'Marble', rarity: 'uncommon' },
    { id: 'cat5', name: 'Saffron', rarity: 'rare' },
    { id: 'cat6', name: 'Inkwell', rarity: 'rare' },
    { id: 'rainbow', name: 'Rainbow Whiskers', rarity: 'legendary' },
  ];
  const lines: string[] = [
    BANNER,
    `import type { CatEntry } from './state';`,
    '',
    `export const GENERATED_CAT_CATALOG: readonly CatEntry[] = [`,
  ];
  for (const e of entries) {
    lines.push('  {');
    lines.push(
      ...fieldLines({
        id: e.id,
        name: e.name,
        rarity: e.rarity,
        scale: e.scale,
        sourceFrame: e.sourceFrame,
        tint: e.tint,
        tintMode: e.tintMode,
      }),
    );
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');
  await fs.writeFile(
    path.join(OUT_DIR, 'cats-catalog.generated.ts'),
    lines.join('\n'),
  );
  return entries.length;
}

async function genDecorations(): Promise<number> {
  let raw: Record<string, DecorationJsonEntry> = {};
  try {
    const text = await fs.readFile(DECORATIONS_JSON, 'utf8');
    raw = JSON.parse(text) as Record<string, DecorationJsonEntry>;
  } catch {
    // file not found — write an empty catalog
  }
  const lines: string[] = [
    BANNER,
    `import type { DecorationEntry } from './state';`,
    '',
    `export const GENERATED_DECORATION_CATALOG: readonly DecorationEntry[] = [`,
  ];
  for (const [id, v] of Object.entries(raw)) {
    lines.push('  {');
    lines.push(
      ...fieldLines({
        id,
        displayName: v.displayName,
        frame: v.frame,
        rarity: v.rarity,
      }),
    );
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');
  await fs.writeFile(
    path.join(OUT_DIR, 'decorations-catalog.generated.ts'),
    lines.join('\n'),
  );
  return Object.keys(raw).length;
}

async function main(): Promise<void> {
  await fs.mkdir(OUT_DIR, { recursive: true });
  const [cosCount, catCount, decCount] = await Promise.all([genCosmetics(), genCats(), genDecorations()]);
  console.log(`[sync] cosmetics=${cosCount} cats=${catCount} decorations=${decCount}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
